Remove exec
cadwallion/publish-rubygems-action pull request #15
Opened 2021-11-28 19:10 UTC by ciremoussadia

We usually use Makefile to run a set of commands. To publish a gem we use the command `make gem.push` which runs first `make gem` (to build the gem) and after pushes it. If the exec command is used it runs only the first command and exit the terminal so the next command is never executed.

We recommend not using the exec command.

2021-11-28 21:34 UTC, CvX commented
Hey! Would you consider submitting this change to https://github.com/discourse/publish-rubygems-action? 😃

2021-11-28 21:53 UTC, ciremoussadia commented
@CvX seems your version is a bit different from this one.

2021-11-30 13:50 UTC, CvX commented
That's correct, the discourse fork expands on the idea of this action, most notably adding the automatic tag creation feature. 😃

2021-11-30 15:54 UTC, cadwallion requested changes
Hello and thank you for the contribution!  I just merged a PR to upgrade to Ruby 3 instead of Ruby 2.7, causing a conflict here.  I'm all for dropping the exec, though.  If you can remove the Ruby version bump I'm happy to merge this.

2021-11-30 18:31 UTC, ciremoussadia commented
@cadwallion done.

2021-12-13 07:57 UTC, ciremoussadia commented
@cadwallion please can you review this.

2022-05-20 14:48 UTC, xjunior approved these changes

2023-03-09 15:31 UTC, merged